<?php return array(
    'root' => array(
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'type' => 'library',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'reference' => '35077a16dfe3dd153b89f32bd5975a7ef8d82600',
        'name' => '__root__',
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'type' => 'library',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'reference' => '35077a16dfe3dd153b89f32bd5975a7ef8d82600',
            'dev_requirement' => false,
        ),
        'bcosca/fatfree-core' => array(
            'pretty_version' => '3.7.3',
            'version' => '3.7.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bcosca/fatfree-core',
            'aliases' => array(),
            'reference' => '3e23ae05384b2f830e99c5888b94118819ed948b',
            'dev_requirement' => false,
        ),
        'firebase/php-jwt' => array(
            'pretty_version' => 'v5.5.1',
            'version' => '5.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../firebase/php-jwt',
            'aliases' => array(),
            'reference' => '83b609028194aa042ea33b5af2d41a7427de80e6',
            'dev_requirement' => false,
        ),
        'gabordemooij/redbean' => array(
            'pretty_version' => 'v5.7.1',
            'version' => '5.7.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../gabordemooij/redbean',
            'aliases' => array(),
            'reference' => '7d1ce93d6c6b8155a3912e4383a8b30db46e2db8',
            'dev_requirement' => false,
        ),
    ),
);
